import sys; sys.argv = sys.argv[:1] + ['none']  # import helpers only; do not rerun stage 3
from stage3_house import *
log('=== shortage: Warehouse has 0 stone_bricks -> Build must refuse without touching world or stock')
save_world(); w0 = world(); before, _ = warehouse_stock(w0)
_, SRC = snapshot()
T = (1019, Y0, 1039)
reset_xform(); select_house(); trig('c')
aim_target(T[0], T[2]); trig('v', 3.0)
trig('build', 1.0); time.sleep(6)
d.screenshot(str(OUT / 'short.png'))
save_world(); w = world()
exp = expect_placed(SRC, T)
record('shortage: build refused, target still air', all(w.block(*p) == 'minecraft:air' for p in exp), '')
after, _ = warehouse_stock(w)
record('shortage: no material deducted', after == before, f'before={dict(before)} after={dict(after)}')
log('=== return the 40 stone bricks through the entry chest, then build succeeds')
x0, z0 = BOX['00']
cmd('clear @s minecraft:stone_bricks')
cmd(f'item replace block {x0} {Y0} {z0} container.0 with minecraft:stone_bricks 40')
time.sleep(15)
aim_target(T[0], T[2])
trig('build', 1.0); time.sleep(6)
save_world(); w = world()
compare(w, exp, 'after restock: build exact', extra_air=box_around(exp))
stock_is(w, dict(house.BOM), 'after restock: charged exactly one BOM')
no_drops(w, 'after restock: no drops')
trig('undo', 1.0); time.sleep(18)
save_world(); stock_is(world(), BOM2, 'final: Warehouse back to full stock after undo')
d.close_screens()
