#!/usr/bin/env python3
"""Generate Copy/Paste's Blueprint block-state matcher from the official 26.3 block report.

The matcher runs at a scanned source block and writes its exact state to
`storage mcc:temp state` = {id:"minecraft:...", properties:{...}} (no `properties` key for a
block without properties), then calls `mcc:blueprint/summon`. It returns fail, without calling
summon, for any block it does not know.

Layout (issue #49):

- `root` / `n_<i>`: a frequency-weighted tree over block IDs. Each node tests its children in
  descending weight order with one `execute if block` per child (a block-tag for a subtree, the
  plain ID for a single block). Every non-root node is only entered for a block inside its tag,
  so its last child is taken without a test; the root tests every child and ends with
  `return fail`.
- `b/<block>`: one leaf per block. Every 26.3 block's states are the full Cartesian product of
  its property values, so each property is resolved on its own instead of enumerating whole
  states:
  - a 2-value property writes its default value, then one test overwrites it with the other;
  - a property with 3+ values calls a shared `p_<i>` function (one per property name + value
    set, testing `#p_<i>[prop=value]`), which returns fail for a value it does not list, and the
    leaf then returns fail without summoning.

Inputs: `scripts/data/blocks-26.3.json`, a compact snapshot of the official report. Refresh it
(and regenerate) from a new report with:

    java -DbundlerMainClass=net.minecraft.data.Main -jar server.jar --reports --output OUT
    python3 scripts/gen-blueprint-matcher.py --report OUT/reports/blocks.json

Without `--report` the matcher is regenerated from the committed snapshot.
"""
from __future__ import annotations
import argparse
import heapq
import json
import re
import shutil
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / 'scripts/data/blocks-26.3.json'
PACK = ROOT / 'datapacks/copy-paste'
FUNC_DIR = PACK / 'data/mcc/function/blueprint/generated'
TAG_DIR = PACK / 'data/mcc/tags/block/blueprint/generated'
NS = 'mcc:blueprint/generated'
AIR = {'minecraft:air', 'minecraft:cave_air', 'minecraft:void_air'}
FANOUT = 4
HEADER = '# Generated by scripts/gen-blueprint-matcher.py from the 26.3 block report; do not edit.\n'

# Relative frequency of blocks in an overworld copy region (terrain plus common building
# blocks). Only the tree shape depends on this; every block resolves the same either way.
# The first matching rule wins; unlisted blocks weigh 1.
WEIGHT_RULES: list[tuple[str, float]] = [
    (r'stone', 4000), (r'dirt', 2000), (r'deepslate', 1500), (r'grass_block', 1500),
    (r'water', 1500), (r'short_grass', 300), (r'andesite|diorite|granite', 300),
    (r'cobblestone', 300), (r'sand', 200), (r'gravel', 200), (r'tuff', 150),
    (r'oak_leaves|spruce_leaves|birch_leaves', 150), (r'glass', 150), (r'oak_planks|spruce_planks', 150),
    (r'stone_bricks', 150), (r'oak_log|spruce_log|birch_log', 100), (r'sandstone', 80),
    (r'smooth_stone', 80), (r'bricks', 60), (r'cobbled_deepslate', 60), (r'tall_grass', 60),
    (r'glass_pane', 60), (r'torch|wall_torch', 40), (r'lava', 40), (r'clay', 30), (r'bedrock', 30),
    (r'coal_ore|iron_ore|copper_ore', 20), (r'snow|snow_block|ice', 20), (r'calcite', 15),
    (r'.+_planks', 50), (r'stripped_.+_(log|wood)', 15), (r'.+_(log|stem)', 30),
    (r'.+_leaves', 30), (r'.+_stairs', 20), (r'.+_slab', 20), (r'polished_.+', 15),
    (r'.+_concrete', 15), (r'.+_stained_glass', 10), (r'.+_stained_glass_pane', 8),
    (r'.+_(fence|wall)', 8), (r'.+_(door|trapdoor)', 6), (r'.+_wool', 6), (r'.+_terracotta', 6),
    (r'.+_carpet', 4), (r'.+_(fence_gate|pressure_plate|button)', 3), (r'.+_bricks', 10),
    (r'(lantern|ladder|chest|crafting_table|furnace|bookshelf|barrel|hay_block|rail)', 5),
]


def weight(block: str) -> float:
    name = block.split(':', 1)[1]
    for pattern, w in WEIGHT_RULES:
        if re.fullmatch(pattern, name):
            return w
    return 1.0


def snapshot_from_report(report: Path) -> dict:
    blocks = {}
    for block, data in json.loads(report.read_text(encoding='utf-8')).items():
        if block in AIR:
            continue
        props = data.get('properties', {})
        default = next(s for s in data['states'] if s.get('default')).get('properties', {})
        # Every matcher shortcut relies on states being the full Cartesian product.
        expected = 1
        for values in props.values():
            expected *= len(values)
        if len(data['states']) != expected:
            raise SystemExit(f'{block}: {len(data["states"])} states, not a Cartesian product of {props}')
        blocks[block] = {'properties': props, 'default': default} if props else {}
    return blocks


def write_snapshot(blocks: dict) -> None:
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    lines = [f'  {json.dumps(k)}: {json.dumps(v, separators=(",", ":"))}' for k, v in blocks.items()]
    SNAPSHOT.write_text('{\n' + ',\n'.join(lines) + '\n}\n', encoding='utf-8', newline='\n')


def build_tree(blocks: list[str]):
    """k-ary Huffman over block weights; a node is a block ID (str) or a list of child nodes."""
    heap = [(weight(b), i, b) for i, b in enumerate(blocks)]
    # Pad with zero-weight placeholders so every merge takes exactly FANOUT nodes.
    counter = len(heap)
    while (len(heap) - 1) % (FANOUT - 1):
        heap.append((0.0, counter, None)); counter += 1
    heapq.heapify(heap)
    while len(heap) > 1:
        group = [heapq.heappop(heap) for _ in range(FANOUT)]
        children = [n for _, _, n in sorted(group, key=lambda g: -g[0]) if n is not None]
        heapq.heappush(heap, (sum(g[0] for g in group), counter, children)); counter += 1
    return heap[0][2]


def leaves(node) -> list[str]:
    return [node] if isinstance(node, str) else [b for c in node for b in leaves(c)]


def generate(blocks: dict, func_dir: Path = FUNC_DIR, tag_dir: Path = TAG_DIR) -> dict:
    for d in (func_dir, tag_dir):
        if d.exists():
            shutil.rmtree(d)
    (func_dir / 'b').mkdir(parents=True)
    tag_dir.mkdir(parents=True)

    def write_func(name: str, lines: list[str]) -> None:
        (func_dir / f'{name}.mcfunction').write_text(HEADER + '\n'.join(lines) + '\n', encoding='utf-8', newline='\n')

    def write_tag(name: str, values: list[str]) -> None:
        (tag_dir / f'{name}.json').write_text(json.dumps({'values': values}, indent=2) + '\n', encoding='utf-8', newline='\n')

    # Shared property functions: one per (property name, value set) with 3+ values. Values are
    # tested most-common-default first, then in report order.
    schemas: dict[tuple[str, tuple[str, ...]], list[str]] = {}
    for block, spec in blocks.items():
        for prop, values in spec.get('properties', {}).items():
            if len(values) > 2:
                schemas.setdefault((prop, tuple(values)), []).append(block)
    schema_ids = {}
    for i, ((prop, values), members) in enumerate(sorted(schemas.items())):
        schema_ids[(prop, values)] = i
        defaults = [blocks[b]['default'][prop] for b in members]
        order = sorted(values, key=lambda v: (-defaults.count(v), values.index(v)))
        write_tag(f'p_{i}', members)
        write_func(f'p_{i}', [
            f'execute if block ~ ~ ~ #{NS}/p_{i}[{prop}={v}] run return run '
            f'data modify storage mcc:temp state.properties.{prop} set value "{v}"' for v in order
        ] + ['return fail'])

    for block, spec in blocks.items():
        name = block.split(':', 1)[1]
        lines = [f'data modify storage mcc:temp state set value {{id:"{block}"}}']
        props = spec.get('properties', {})
        for prop, values in props.items():
            if len(values) == 2:
                default = spec['default'][prop]
                other = values[1] if values[0] == default else values[0]
                lines += [
                    f'data modify storage mcc:temp state.properties.{prop} set value "{default}"',
                    f'execute if block ~ ~ ~ {block}[{prop}={other}] run '
                    f'data modify storage mcc:temp state.properties.{prop} set value "{other}"',
                ]
            else:
                lines.append(f'execute unless function {NS}/p_{schema_ids[(prop, tuple(values))]} run return fail')
        lines.append('return run function mcc:blueprint/summon with storage mcc:temp')
        write_func(f'b/{name}', lines)

    tree = build_tree(list(blocks))
    counter = [0]

    def emit(node, fname: str, is_root: bool) -> None:
        lines = []
        for idx, child in enumerate(node):
            if isinstance(child, str):
                target, test = f'{NS}/b/{child.split(":", 1)[1]}', child
            else:
                tag = f'n_{counter[0]}'; counter[0] += 1
                write_tag(tag, leaves(child))
                emit(child, tag, False)
                target, test = f'{NS}/{tag}', f'#{NS}/{tag}'
            if idx == len(node) - 1 and not is_root:
                lines.append(f'return run function {target}')
            else:
                lines.append(f'execute if block ~ ~ ~ {test} run return run function {target}')
        if is_root:
            lines.append('return fail')
        write_func(fname, lines)

    emit(tree, 'root', True)
    return {'blocks': len(blocks), 'nodes': counter[0] + 1, 'schemas': len(schemas)}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--report', type=Path, help='official blocks.json; refreshes the committed snapshot')
    ap.add_argument('--check', action='store_true', help='fail if the committed matcher differs from a fresh build')
    args = ap.parse_args()
    if args.report:
        write_snapshot(snapshot_from_report(args.report))
    blocks = json.loads(SNAPSHOT.read_text(encoding='utf-8'))
    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            generate(blocks, Path(tmp) / 'function', Path(tmp) / 'tags')
            for fresh, committed in ((Path(tmp) / 'function', FUNC_DIR), (Path(tmp) / 'tags', TAG_DIR)):
                want = {p.relative_to(fresh): p.read_bytes() for p in fresh.rglob('*') if p.is_file()}
                # a Windows checkout with core.autocrlf has CRLF files; the committed blobs are LF
                have = {p.relative_to(committed): p.read_bytes().replace(b'\r\n', b'\n')
                        for p in committed.rglob('*') if p.is_file()}
                if want != have:
                    stale = sorted(str(p) for p in set(want) | set(have) if want.get(p) != have.get(p))
                    raise SystemExit(f'{committed} is stale ({len(stale)} files, e.g. {stale[:3]}); '
                                     'run scripts/gen-blueprint-matcher.py')
        print('Blueprint matcher is up to date')
        return
    stats = generate(blocks)
    print(f'Generated Blueprint matcher: {stats["blocks"]} blocks, {stats["nodes"]} tree nodes, '
          f'{stats["schemas"]} shared property functions')


if __name__ == '__main__':
    main()
