#!/usr/bin/env python3
"""Generate Copy/Paste's item tables from the official server reports.

- key: item id -> translation key; chat shows {"translate": key}, so every player sees item
  names in their own game language.
- max: item id -> max stack size (only where it is not 64), to know how much a player's
  inventory can take back on Undo.

    java -DbundlerMainClass=net.minecraft.data.Main -jar server.jar --reports --output OUT
    python3 scripts/gen-item-names.py OUT/reports
"""
from __future__ import annotations
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'datapacks/copy-paste/data/mcc/function/names/load.mcfunction'


def main() -> None:
    items = Path(sys.argv[1]) / 'minecraft/components/item'
    table = {}
    stacks = {}
    for f in sorted(items.glob('*.json')):
        data = json.loads(f.read_text(encoding='utf-8'))
        name = data.get('components', data).get('minecraft:item_name')
        if isinstance(name, dict) and isinstance(name.get('translate'), str):
            table[f'minecraft:{f.stem}'] = name['translate']
        size = data.get('components', data).get('minecraft:max_stack_size', 64)
        if size != 64:
            stacks[f'minecraft:{f.stem}'] = size
    if len(table) < 1000:
        raise SystemExit(f'only {len(table)} item names found under {items}')
    snbt = '{' + ','.join(f'"{k}":"{v}"' for k, v in table.items()) + '}'
    max_snbt = '{' + ','.join(f'"{k}":{v}' for k, v in stacks.items()) + '}'
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text('# Generated by scripts/gen-item-names.py from the 26.3 server reports; do not edit.\n'
                      '# key: item id -> translation key (item names in each player\'s language).\n'
                      '# max: item id -> max stack size where it is not 64.\n'
                      f'data modify storage mcc:names key set value {snbt}\n'
                      f'data modify storage mcc:names max set value {max_snbt}\n', encoding='utf-8')
    print(f'{len(table)} item names, {len(stacks)} non-64 stack sizes -> {TARGET.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
